---
name: Build and Release
on:
  workflow_dispatch:
    inputs:
      release_name:
        description: "Release Version (e.g. v0.0.0)"
        required: true
        type: string

permissions:
  id-token: write
  contents: write
  attestations: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: rustup update
      - run: rustup target add wasm32-unknown-unknown
      - run: cargo version

      # 1️⃣: Tag the built wasm file with it's source-repo.
      - uses: stellar/stellar-cli@v22.0.1
        with:
          version: "22.0.1"
      - run:
          stellar contract build --meta source_repo=github:${{ github.repository
          }}

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hello.wasm
          path: target/wasm32-unknown-unknown/release/hello.wasm

      # 2️⃣: Build the attestation for the wasm file.
      - name: Build Attestation for Release (release only)
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: hello.wasm
          subject-path: target/wasm32-unknown-unknown/release/hello.wasm

      # 3️⃣: Make a new release.
      - name: Make a new Release
        id: release
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: '${{ github.event.inputs.release_name }}',
              target_commitish: '${{ github.sha }}',
              make_latest: 'true'
            });

            const { data } = response;
            console.log(data.id);

      # 4️⃣: Upload the wasm file to the release.
      - name: Upload to Release
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            await github.rest.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: '${{ steps.release.outputs.result }}',
              name: 'hello.wasm',
              data: fs.readFileSync('target/wasm32-unknown-unknown/release/hello.wasm'),
            });
